### ISSUE TITLE
RabbitMq queues reset after 7 hours

### ISSUE THREAD

**Issue by fedemennite** [tesonep/pharo-testWorkers#15]
This issue is apparently reproducible by having a run to last at least 7 hours.
Currently workaround by adding more processing power to the hardware used.
@sonibla can offer further details.

**Comment by tesonep** [comment]
@sonibla is it possible to retry it, letting the worker started, so we can check if there is any error in the Pharo side?

**Comment by sonibla** [comment]
I had this issue 2 times and it's difficult to reproduce
I ran tests several times in about 8 hours successfully

**Comment by tesonep** [comment]
I have let it run a lot of time and I have reproduced it without the fix of @sonibla 
After I applied the fix, I couldn't reproduce the issue. 
I have seen some disconnections during the time I let it run, but after the fix, the workers reconnect seamlessly.

**Comment by tesonep** [comment]
I think it is related to the other issue. It was the same error not handling correctly the exception

**Comment by fedemennite** [comment]
This is confirmed fixed on our side.
