### ISSUE TITLE
On crash or stop of the image or the watchdog, the RabbitMq queue should be voided and emptied

### ISSUE THREAD

**Issue by VincentBlondeau** [tesonep/pharo-testWorkers#5]
In a kill event of the images (master or slave), it seems that the queues of the rabbit mq are not emptied and can still contain some requests: run some tests that are in the queue buffer (not delivered yet) or pong answers.
I think that it is due to the fact that the same queue is used again to interact between the master and the workers.

There should be a process to either :
- clean the queue
- create a new queue with a random id

**Comment by tesonep** [comment]
@VincentBlondeau I have fixed this, can you try it?

**Comment by fedemennite** [comment]
This was indeed working for us since quite some time,
Can be closed at your convenience
