### ISSUE TITLE
TestRequest queue contains all the tests to be run and is not reset when we trigger a run

### ISSUE THREAD

**Issue by VincentBlondeau** [tesonep/pharo-testWorkers#6]
TestRequest queue should be reset each time Dr Test asks a new test run.
So far the new testsrequests adds to the queue and the old tests are still there even if they are not needed anymore.

We should be able to clean the queue of a given batch run.

**Comment by tesonep** [comment]
@VincentBlondeau I have changed to clean up the queue on the demand of new tests.

**Comment by VincentBlondeau** [comment]
Closing request. Should be fixed.
