### ISSUE TITLE
Unhandled connection errors in the watchdog pinger process

### ISSUE THREAD

**Issue by fedemennite** [tesonep/pharo-testWorkers#9]
This doesn't happen very often.
In such situation, leaving the debugger open allows the test run to continue.
Stack trace attached.
Food for thought, is a pinging from the master really needed given the workers images are already ponging?
[pinger_stack.txt](https://github.com/tesonep/pharo-testWorkers/files/5857797/pinger_stack.txt)

**Comment by tesonep** [comment]
@VincentBlondeau I have removed the ping and now there is only the pong side from the workers to the watchdog.
Can you see if that is better?

**Comment by fedemennite** [comment]
We didn't manage to do a full testsuite run yes but this specific issue didn't show up anymore.

**Comment by fedemennite** [comment]
Still not showing up anymore. Closing
